import api, { travelApi } from './api';

const travelPlanService = {
    getAll: () => travelApi.get('/travel-plans').then(r => r.data),
    getById: (id) => travelApi.get(`/travel-plans/${id}`).then(r => r.data),
    create: (data) => travelApi.post('/travel-plans', data).then(r => r.data),
    update: (id, data) => travelApi.put(`/travel-plans/${id}`, data).then(r => r.data),
    delete: (id) => travelApi.delete(`/travel-plans/${id}`),
    getDestinations: (pid) => travelApi.get(`/travel-plans/${pid}/destinations`).then(r => r.data),
    addDestination: (pid, d) => travelApi.post(`/travel-plans/${pid}/destinations`, d).then(r => r.data),
    updateDestination: (pid, id, d) => travelApi.put(`/travel-plans/${pid}/destinations/${id}`, d).then(r => r.data),
    deleteDestination: (pid, id) => travelApi.delete(`/travel-plans/${pid}/destinations/${id}`),
    getActivities: (pid) => travelApi.get(`/travel-plans/${pid}/activities`).then(r => r.data),
    addActivity: (pid, a) => travelApi.post(`/travel-plans/${pid}/activities`, a).then(r => r.data),
    updateActivity: (pid, id, a) => travelApi.put(`/travel-plans/${pid}/activities/${id}`, a).then(r => r.data),
    deleteActivity: (pid, id) => travelApi.delete(`/travel-plans/${pid}/activities/${id}`),
    getExpenses: (pid) => travelApi.get(`/travel-plans/${pid}/expenses`).then(r => r.data),
    addExpense: (pid, e) => travelApi.post(`/travel-plans/${pid}/expenses`, e).then(r => r.data),
    updateExpense: (pid, id, e) => travelApi.put(`/travel-plans/${pid}/expenses/${id}`, e).then(r => r.data),
    deleteExpense: (pid, id) => travelApi.delete(`/travel-plans/${pid}/expenses/${id}`),
    getChecklist: (pid) => travelApi.get(`/travel-plans/${pid}/checklist`).then(r => r.data),
    addChecklistItem: (pid, c) => travelApi.post(`/travel-plans/${pid}/checklist`, c).then(r => r.data),
    toggleChecklist: (pid, id) => travelApi.patch(`/travel-plans/${pid}/checklist/${id}/toggle`).then(r => r.data),
    deleteChecklistItem: (pid, id) => travelApi.delete(`/travel-plans/${pid}/checklist/${id}`),
    createShareToken: (pid, accessType) => travelApi.post(`/travel-plans/${pid}/share`, { accessType }).then(r => r.data),
    getByToken: (token) => travelApi.get(`/shared/${token}`).then(r => r.data),
    acceptShareToken: (token) => travelApi.post(`/shared/${token}/accept`).then(r => r.data),
    getSharedPlans: () => travelApi.get('/travel-plans/shared').then(r => r.data),
};
export default travelPlanService;